### ISSUE TITLE
Ghost Monthly Goal Hours

### ISSUE THREAD

**Issue by codeecantin** [toopriddy/mytime#323] opened 2017-10-03 19:22 UTC
Where? Statistic page
What? Pioneer Current Month’s hourly goal shows incorrect amount. Even with total sweep of app and document data, problem still exists.

**Comment by codeecantin** [comment] 2017-10-03 19:23
![55324be1-b784-4a79-b0a0-07bd86783c28](https://user-images.githubusercontent.com/32496062/31144451-c6ac5e4e-a84e-11e7-801b-04227b08133a.png)

**Comment by toopriddy** [comment] 2017-10-04 13:43
Hello, MyTime is calculating your average monthly goal to reach the real yearly goal. If there are no hours for the first month in the service year then the future months will have to have on average more than 70 hours to be able to reach the year goal.

If you are starting pioneering in October, then change MyTime->More->Settings-> Pioneer Start Date to be October so it calculates appropriately.

I hope this helps, I am going to close this issue as not a bug, if you have future questions about this then please send me an email toopriddy@gmail.com

**Comment by codeecantin** [comment] 2017-10-04 20:27
Thanks so much for answering this!
I guess I didn’t expect it to divide the missed time over the left over months of the service year.

I wish there was an option to have the missed time added to the next month only.

**Closed** 2017-10-04 21:03 UTC

**Comment by toopriddy** [comment] 2017-10-05 00:25
You can go to the "Statistics" tab, tap on "Edit" and then modify the
previous month for the hours that you had on it to help the calculation if
you are just now using MyTime.

I hope this helps.

**Comment by codeecantin** [comment] 2017-10-05 01:08
Thanks so much

Sent from my iPhone

On Oct 4, 2017, at 8:25 PM, toopriddy <notifications@github.com<mailto:notifications@github.com>> wrote:

You can go to the "Statistics" tab, tap on "Edit" and then modify the
previous month for the hours that you had on it to help the calculation if
you are just now using MyTime.

I hope this helps.
