### ISSUE TITLE
Start Time-crashes App 

### ISSUE THREAD

**Issue by b-alex-1995** [toopriddy/mytime#371] opened 2019-10-03 01:03 UTC
In iOS 13.1.2, MyTime version 3.10.4 (1) build date Sept 28,2019,
Clicking Start Time from the Hours tab starts time then crashes app. On reopen, time is shown as starting but when user touches Stop Time, it stops time counting and crashes again.

**Comment by toopriddy** [comment] 2019-10-08 13:50
duplicate of https://github.com/toopriddy/mytime/issues/366

**Closed as completed** 2019-10-08 13:50 UTC
