### ISSUE TITLE
Sorting not working

### ISSUE THREAD

**Issue by flashoflight1** [toopriddy/mytime#385] opened 2019-12-07 13:41 UTC
The sort by buttons in my time no longer work. 

Thanks 
Steve Mathey

**Comment by PAMELA3BLACK** [comment] 2019-12-21 12:57
Sorting tabs don’t work on iphone 11 ProMax

**Comment by toopriddy** [comment] 2019-12-22 15:28
Sorry for the trouble. This is a duplicate of https://github.com/toopriddy/mytime/issues/377 please see the workaround while we wait on Apple to fix the bug

**Closed as completed by toopriddy** 2019-12-22 15:28 UTC
