### ISSUE TITLE
Time Clock 

### ISSUE THREAD

**Issue by tban53009** [toopriddy/mytime#369] opened 2019-09-20 14:47 UTC
Everytime I start the clock on mytime  I cannot stop the time. It for some reason freezes and I have to get out of the app completely and close it. Then open it up and i can stop the timer or delete entries. I have a iphone 7 plus and running the latest software.

**Comment by toopriddy** [comment] 2019-09-30 13:55
Duplicate of https://github.com/toopriddy/mytime/issues/347  please see the workaround in that issue to help get around this apple bug they have not yet fixed

**Closed as completed by toopriddy** 2019-09-30 13:55 UTC
